# Generated by Django 5.0.6 on 2026-06-16 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Sala')),
                ('capacity', models.PositiveIntegerField(editable=False, verbose_name='Capacidad Total')),
                ('rows', models.PositiveIntegerField(verbose_name='Cantidad de Filas')),
                ('columns', models.PositiveIntegerField(verbose_name='Butacas por Fila')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Soft Delete'), ('CANCEL', 'Canceled')], max_length=10)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.CharField(max_length=50)),
                ('snapshot_before', models.JSONField(blank=True, null=True)),
                ('snapshot_after', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duración (min)')),
                ('rating_classification', models.CharField(choices=[('ATP', 'ATP'), ('+13', '+13'), ('+16', '+16'), ('+18', '+18')], max_length=10, verbose_name='Clasificación')),
                ('release_date', models.DateField(verbose_name='Fecha de Estreno')),
                ('poster_url', models.URLField(verbose_name='URL del Afiche')),
                ('trailer_url', models.URLField(verbose_name='URL del Trailer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('genres', models.ManyToManyField(to='catalog.genre', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Inicio')),
                ('end_time', models.DateTimeField(editable=False, null=True, verbose_name='Fin (Calculado)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de Cancelación')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='catalog.movie', verbose_name='Película')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.room', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('status', models.CharField(choices=[('completed', 'Completada'), ('pending_refund', 'Reembolso Pendiente'), ('refunded', 'Reembolsada')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_orders', to='catalog.screening')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='catalog.room')),
            ],
            options={
                'unique_together': {('room', 'row', 'number')},
            },
        ),
    ]
