# Generated by Django 5.0.6 on 2026-06-19 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Formato (Ej. 2D, 3D, IMAX)')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto extra que se suma al precio base del ticket.', max_digits=5, verbose_name='Recargo por formato (Bs.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Formato de Proyección',
                'verbose_name_plural': 'Formatos de Proyección',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Idioma / Versión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Versión de Idioma',
                'verbose_name_plural': 'Versiones de Idioma',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Entrada')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Base (Bs.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Tipo de Ticket',
                'verbose_name_plural': 'Tipos de Ticket',
            },
        ),
    ]
