# Generated by Django 5.0.6 on 2026-06-16 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Soft Delete')], max_length=10, verbose_name='Acción')),
                ('table_name', models.CharField(max_length=50, verbose_name='Tabla Afectada')),
                ('record_id', models.CharField(max_length=50, verbose_name='ID del Registro')),
                ('snapshot_before', models.JSONField(blank=True, null=True, verbose_name='Snapshot Antes')),
                ('snapshot_after', models.JSONField(blank=True, null=True, verbose_name='Snapshot Después')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
