# Generated by Django 5.0.6 on 2026-06-19 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_format_language_tickettype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Log de Auditoría', 'verbose_name_plural': 'Logs de Auditoría'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['room', 'row_label', 'column_number'], 'verbose_name': 'Butaca', 'verbose_name_plural': 'Butacas'},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rows',
        ),
        migrations.AddField(
            model_name='room',
            name='cleaning_time_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Tiempo requerido antes de la siguiente función.', verbose_name='Tiempo de Limpieza (Min)'),
        ),
        migrations.AddField(
            model_name='room',
            name='grid_columns',
            field=models.PositiveIntegerField(default=10, help_text='Ej. 15', verbose_name='Columnas (Cuadrícula)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='grid_rows',
            field=models.PositiveIntegerField(default=10, help_text='Ej. 10', verbose_name='Filas (Cuadrícula)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='seat',
            name='column_number',
            field=models.PositiveIntegerField(default=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='row_label',
            field=models.CharField(default=10, max_length=5, verbose_name='Fila'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP / Preferencial'), ('wheelchair', 'Silla de Ruedas'), ('corridor', 'Pasillo (Vacío)')], default='normal', max_length=20, verbose_name='Tipo de Butaca'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='catalog.room', verbose_name='Sala'),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
    ]
