# Generated by Django 5.0.6 on 2026-06-21 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_screening_options_remove_screening_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='catalog.ticketorder')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.seat')),
            ],
        ),
    ]
