# Generated by Django 5.0.6 on 2026-06-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_ticketorder_total_price_alter_ticketorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('wheelchair', 'Silla de Ruedas'), ('corridor', 'Pasillo (Vacío)')], default='normal', max_length=20, verbose_name='Tipo de Butaca'),
        ),
    ]
